version = 1
test_patterns = [
  "*_test.go"
]
exclude_patterns = [
  "examples/**",
  "vendor/**"
]
[[analyzers]]
name = "go"
enabled = true
  [analyzers.meta]
  import_path = "github.com/messagebird/sachet"
